services:
  axelor:
    build:
      dockerfile: Dockerfile
    environment:
      AXELOR_CONFIG_DB_DEFAULT_URL: jdbc:postgresql://postgres:5432/axelor
      AXELOR_CONFIG_DB_DEFAULT_USER: axelor
      AXELOR_CONFIG_DB_DEFAULT_PASSWORD: axelorPWD  # !!! When you change this, change also the password in "init-database.sh" !!!
      AXELOR_CONFIG_APPLICATION_HOME: localhost:8080
      AXELOR_CONFIG_APPLICATION_MODE: dev
      AXELOR_CONFIG_APPLICATION_LOCALE: de_DE
      AXELOR_CONFIG_APPLICATION_BASE-URL: localhost
      AXELOR_CONFIG_DATA_UPLOAD_DIR: "/opt/data/attachments"
      AXELOR_CONFIG_DATA_UPLOAD_MAX-SIZE: 100
      AXELOR_CONFIG_DATA_EXPORT_DIR: "/opt/data/export"
      AXELOR_CONFIG_DATA_IMPORT_DEMO-DATA: true
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - axelor_data_files:/opt/data
      - axelor_data_tomcat:/bitnami/tomcat/webapps
    ports:
      - "8080:8080"
    networks:
      - axelor
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:16.9-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_PASSWORD: superuser
    ports:
      - "5432:5432"
    networks:
      - axelor

volumes:
  postgres_data:
    driver: local
  axelor_data_files:
    driver: local
  axelor_data_tomcat:
    driver: local

networks:
  axelor:
