version: 3

includes:
  local:
    taskfile: .tasks/local.yaml

env:
  AXELOR_REPO: axelor/axelor-open-suite

tasks:
  get-artifact:
    desc: Downloads the lastest Tomcat .war release of Axelor Open Suite
    silent: true
    cmds:
      - ./scripts/get-war-file.sh {{.CLI_ARGS}}

  build:
    desc: Builds the docker image for latest Axelor release version
    cmds:
      - docker buildx build -t axelor-os:{{ .VERSION }} .
