version: 3

includes:
  dev:
    taskfile: .tasks/dev.yaml

env:
  AXELOR_REPO: axelor/axelor-open-suite
  PMOSCODE_DOCKER: pmoscode/axelor-open-suite

tasks:
  get-artifact:
    desc: Downloads the lastest Tomcat .war release of Axelor Open Suite
    silent: true
    cmds:
      - ./scripts/get-war-file.sh {{.CLI_ARGS}}

  get-missing-artifacts:
    desc: Builds the missing artifact versions.
    cmds:
      - ./scripts/get-missing-releases.sh
