name: Update DockerHub description

on:
  workflow_dispatch:

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          short-description: Open source ERP and BPM platform.
          readme-filepath: README-DOCKER-HUB.md
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: pmoscode/axelor-open-suite